export const availableIcons = [
  "AngularIcon",
  "ApacheIcon",
  "ArduinoIcon",
  "AstroIcon",
  "CssIcon",
  "DockerIcon",
  "FigmaIcon",
  "FireBaseIcon",
  "GitColoredIcon",
  "HtmlIcon",
  "JavaIcon",
  "JavaScriptIcon",
  "LinuxIcon",
  "MysqlIcon",
  "NextJsIcon",
  "NodeIcon",
  "NpmIcon",
  "PhpIcon",
  "PrettierIcon",
  "PrismaIcon",
  "PythonIcon",
  "ReactIcon",
  "SymfonyIcon",
  "TailwindIcon",
  "TypesCriptIcon",
  "VirtualBoxIcon",
  "ViteIcon",
  "VsCodeIcon",
  "VueJsIcon",
  "JwtIcon",
  "OllamaIcon",
] as const;

export type IconName = (typeof availableIcons)[number];
